#pragma once
/*游戏核心机制中的重要常量*/

#define CONSUME_MANA1 0
#define CONSUME_MANA2 1

#define EFFECTDIR_TO_SETTLE 0
#define EFFECTDIR_TO_M_EFFECTLIST 1
#define EFFECTDIR_TO_E_EFFECTLIST 2

#define TRIGGER_GAME_START 1000
#define TRIGGER_ROUND_START 2000
#define TRIGGER_ROUND_END 3000
#define TRIGGER_M_A_CARD_USED 4000
#define TRIGGER_E_A_CARD_USED 25000
#define TRIGGER_M_GOT_HURT 5000
#define TRIGGER_M_HURT_SOMEONE 6000
#define TRIGGER_M_GOT_RECOVER 7000
#define TRIGGER_M_GOT_MANA1_UP 8000
#define TRIGGER_M_GOT_MANA2_UP 9000
#define TRIGGER_M_HANDP_REMOVE 10000
#define TRIGGER_M_DSCDP_REMOVE 11000
#define TRIGGER_M_HANDP_INSERT 12000
#define TRIGGER_M_DSCDP_INSERT 13000
#define TRIGGER_E_GOT_HURT 14000
#define TRIGGER_E_HURT_SOMEONE 15000
#define TRIGGER_E_GOT_RECOVER 16000
#define TRIGGER_E_GOT_MANA1_UP 17000
#define TRIGGER_E_GOT_MANA2_UP 18000
#define TRIGGER_E_HANDP_REMOVE 19000
#define TRIGGER_E_DSCDP_REMOVE 20000
#define TRIGGER_E_HANDP_INSERT 21000
#define TRIGGER_E_DSCDP_INSERT 22000
#define TRIGGER_M_EFFECT_SETTLE 23000
#define TRIGGER_E_EFFECT_SETTLE 24000

#define EFFECT_AFTERWARDS_GO 0
#define EFFECT_AFTERWARDS_STAY 1
#define EFFECT_AFTERWARDS_COUNTDOWN 2

#define EFFECT_TYPE_VIRUS 99

#define CARD_TYPE_ATTACK 0
#define CARD_TYPE_RECOVER 1
#define CARD_TYPE_FUNCTION 2
#define CARD_TYPE_MAGIC 3

#define EXE_NOTE_E_HURT 13
#define EXE_NOTE_E_RECOVER 14
#define EXE_NOTE_E_MANA1_UP 15
#define EXE_NOTE_E_MANA2_UP 16
#define EXE_NOTE_E_MANA1_DOWN 17
#define EXE_NOTE_E_MANA2_DOWN 18
#define EXE_NOTE_E_HANDP_REMOVE 19
#define EXE_NOTE_E_HANDP_INSERT 20
#define EXE_NOTE_E_DSCDP_REMOVE 21
#define EXE_NOTE_E_DSCDP_INSERT 22
#define EXE_NOTE_E_DRCDP_REMOVE 23
#define EXE_NOTE_E_DRCDP_INSERT 24
#define EXE_NOTE_E_EFFECTQ_REMOVE 25
#define EXE_NOTE_E_EFFECTQ_INSERT 26

#define EXE_NOTE_M_HURT 27
#define EXE_NOTE_M_RECOVER 28
#define EXE_NOTE_M_MANA1_UP 29
#define EXE_NOTE_M_MANA2_UP 30
#define EXE_NOTE_M_MANA1_DOWN 31
#define EXE_NOTE_M_MANA2_DOWN 32
#define EXE_NOTE_M_HANDP_REMOVE 33
#define EXE_NOTE_M_HANDP_INSERT 34
#define EXE_NOTE_M_DSCDP_REMOVE 35
#define EXE_NOTE_M_DSCDP_INSERT 36
#define EXE_NOTE_M_DRCDP_REMOVE 37
#define EXE_NOTE_M_DRCDP_INSERT 38
#define EXE_NOTE_M_EFFECTQ_REMOVE 39
#define EXE_NOTE_M_EFFECTQ_INSERT 40


#define CD_TRIGGER_ROUNDSTART 0
#define CD_TRIGGER_ROUNDEND 1
#define CD_TRIGGER_AFTEREFFECT 2