#pragma once

/*UI中使用的众多参数*/
#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080

#define TOP_DASHBOARD_HEIGHT 300

#define EXHIBI_WIDTH 320
#define CARD_WIDTH 240
#define CARD_HEIGHT 360
#define BLOCK_WIDTH 260
#define BLOCK_HEIGHT 390
#define DIALOG_MARGIN_WIDTH 360
#define DIALOG_MARGIN_HEIGHT 320
#define MDASHBOARD_WIDTH 360
#define MHANDPILE_HEIGHT 400
#define MHANDPILE_PADDING 18
#define EHANDPILE_HEIGHT 400
#define EHANDPILE_WIDTH 400
#define EHANDPILE_PADDING 5
#define EHANDPILE_PADDINGLEFT 0

#define ROLE_CARD_WIDTH 320
#define ROLE_CARD_HEIGHT 353

#define ACTIONS_SCALE 3
#define ACTIONS_MOVE 4
#define ACTIONS_FLIP 5


#define EFFECTS_WIDTH 500
#define EFFECT_WIDTH 64
#define EFFECTS_HEIGHT 64

#define COUNT_TROPHY_SIZE 300

#define UNITVIEW_WIDTH 360
#define UNIVIEW_HEIGHT 420	